export const publicRoutes = [
  "/",
  "/uzmanlar",
  "/uzmanlar/[slug]",
  "/testler",
  "/testler/[slug]",
  "/blog",
  "/blog/[slug]",
  "/paketler",
  "/hakkimizda",
  "/nasil-calisir",
  "/uzman-basvurusu",
  "/iletisim",
  "/kurumsal",
  "/sss",
  "/kvkk",
  "/giris",
  "/kayit",
  "/sifre-sifirla",
] as const;
